version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: cms_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: course_management_system
      MYSQL_USER: cms_user
      MYSQL_PASSWORD: cms_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init.sql:/docker-entrypoint-initdb.d/mysql-init.sql
    networks:
      - cms_network
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: cms_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: cms_user
      PMA_PASSWORD: cms_password
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - cms_network
    restart: unless-stopped

volumes:
  mysql_data:
    driver: local

networks:
  cms_network:
    driver: bridge
