# Production Profile Configuration
spring:
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/cms_database}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
  
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    com.university.cms: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
